modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Charlie-Ward/LousyUtils/issues" #optional

[[mods]] #mandatory
modId="lousyutils" #mandatory
version="0.0.1-1.19" #mandatory
displayName="LousyUtils" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Charlie-Ward/LousyUtils" #optional
logoFile="examplemod.png" #optional
credits="" #optional
authors="LousyBoi" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod full of utility items. All features added are craftable in survival.
'''

[[dependencies.lousyutils]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.lousyutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
